export const TITLE_MAIL_REGISTER = 'FACEBOOK_V2-XÁC MINH ĐĂNG KÝ TÀI KHOẢN';
export const TITLE_MAIL_FORGETPASSWORD = 'FACEBOOK_V2-XÁC MINH TÀI KHOẢN';
export const TITLE_MAIL_RESETPASSWORD = 'FACEBOOK_V2-THAY ĐỔI MẬT KHẨU THÀNH CÔNG';
